# -*- coding: utf-8 -*-
"""Histogramas_BoxPlots_e_ScatterPlots_com_Plotly.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ru33UozVrFG4uNzHoqlrZosUDFvzqKqj
"""

# Commented out IPython magic to ensure Python compatibility.
#A partir do plotly versão 4.0, todas as funcionalidades relacionadas ao Chart Studio foram movidas para a chart_studiobiblioteca. 
#https://plotly.com/python/v4-migration/#online-features-plotlyplotly-moved-to-chartstudio-package
# %pip install chart-studio

import pandas as pd
import numpy as np
import cufflinks as cf
import chart_studio

from sklearn.preprocessing import StandardScaler

#https://plotly.com/python/getting-started-with-chart-studio/
chart_studio.tools.set_credentials_file(username='giovanebmr', api_key='cK2EmejarWAwyyYW9PN7')

#colocando o gráfico no modo de compartilhamento privado
chart_studio.tools.set_config_file(world_readable=False, sharing='private')

caminho = '/content/df_vendas_novo.csv'
data = pd.read_csv(caminho)
data.columns = ['Data Venda','Data Envio','ID Loja','ID Produto','ID Cliente','No. Venda','Custo Unitário','Preço Unitário','Quantidade','Valor Desconto','Valor Venda','Produto','Fabricante','Marca','Classe','Cor','custo','lucro','Tempo de envio']

df = data[ ['Valor Venda','lucro','Quantidade'] ]

lucro = data.lucro
print(lucro)

lucro.iplot(kind='histogram', filename='histograma-lucro')

colunas = ['Valor Venda','lucro','Quantidade']
dados = data[colunas].values
print(dados)

dados_scaled = StandardScaler().fit_transform(dados)
df = pd.DataFrame( dados_scaled )

df.columns = colunas

df.iplot(kind='histogram', filename='histograma-multiplo')

df.iplot(kind='histogram', subplots=True, filename='histograma-mult-subplot')

df.iplot(kind='histogram', subplots=True, shape=(3,1), filename='histograma-mult-subplot-shape1')

df.iplot(kind='histogram', subplots=True, shape=(1,3), filename='histograma-mult-subplot-shape2')

"""# **BoxPlots**"""

df.iplot(kind='box', filename='boxplots')

"""# **Scatter Plots**"""

import chart_studio.plotly as py

#['Valor Venda','lucro','Quantidade']

fig = {
    'data' : [
            {'x':df.lucro, 'y':df['Valor Venda'],'mode':'markers', 'name':'Lucro'},
            {'x':df.Quantidade, 'y':df['Valor Venda'],'mode':'markers', 'name':'Quantidade'},
    ],
    'layout': {
        'xaxis':{'title':''},
        'yaxis':{'title':'Deslocamento Padronizado'}
    }
}
py.iplot(figure_or_data=fig, filename='scatterplot-lucro',sharing='public')